version: '2.1'

services:
  5monkeys:
    image: 5monkeys
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js